Repository wecode-bootcamp-korea/50-2nd-ORONAMIN_C-frontend, pull requests merged in 2023-11, with the labels that each got.

#2 메뉴리스트 구성 완료, 장바구니담기버튼 활성화/서브카테고리메뉴(dropdown)기능 추가확인필요
  public/data/productList.json
  public/data/sample.json
  src/Router.js
  src/components/CartBtn/CartBtn.js
  src/components/CartBtn/CartBtn.scss
  src/components/Category/Category.js
  src/components/Category/Category.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 수정 요청

#3 제품상세페이지 ui구성중
  public/data/productDetail.json
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/ProductList.js
Labels: 멘토 리뷰 요청

#1 Feature/cart
  README.md
  public/data/data.json
  public/data/user.json
  src/Router.js
  src/pages/Admin/Admin.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Pay/Pay.js
  src/pages/Pay/Pay.scss
Labels: 멘토 리뷰 요청

#4 Feature/mainpage
  public/images/Logo.png
  public/images/alt1.png
  public/images/alt2.png
  public/images/alt3.png
  public/images/alt4.png
  public/images/img1-1.png
  public/images/img1-2.png
  public/images/img1-3.png
  public/images/img1-4.png
  public/images/img1-5.png
  public/images/img1-6.png
  public/images/img1-7.png
  public/images/img1-8.png
  public/images/img1.png
  public/images/img2.png
  public/images/img3.png
  public/images/item1.png
  public/images/item2.png
  public/images/item3.png
  public/images/item4.png
  public/images/item5.png
  public/images/item6.png
  public/images/item7.png
  public/images/item8.png
  public/images/item9.png
  public/images/left_arrow.png
  public/images/right_arrow.png
  public/images/slideimg01.png
  public/images/slideimg02.png
  public/images/slideimg03.png
  public/images/slideimg04.png
  public/images/testimg.heic
  public/images/wideimg01.png
  public/video/L'Or de J'adore, the new perfume.mp4
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/map.js
  src/pages/main/Main.js
  src/pages/main/Main.scss
Labels: 멘토 리뷰 요청

#8 info
  public/images/info1_1.png
  public/images/info2.png
  public/images/info3.png
  public/images/info4.png
  public/images/info5.png
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Info/Info.js
  src/pages/Info/Info.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/slideData.js
  src/pages/main/Main.js
  src/pages/main/Main.scss
Labels: 멘토 리뷰 요청

#6 Add: signup, login 페이지 작업 중
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/logo.png
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 완료
